modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/The-Aether-Team/Cumulus/issues"

[[mods]]
modId="cumulus_menus"
version="${file.jarVersion}"
displayName="Cumulus"
updateJSONURL="https://github.com/The-Aether-Team/Cumulus/raw/1.20.4-develop/update.json"
displayURL="https://modrinth.com/mod/cumulus"
logoFile="cumulus.png"
credits="The Aether Team; kingbdogz, for the original Main Menu API that this is inspired by"
authors="bconlon"
description='''
    A library for custom menu registration.'''

[[dependencies.cumulus_menus]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cumulus_menus]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.20.5)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="cumulus_menus.mixins.json"